In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.decomposition import PCA
from sklearn.impute import SimpleImputer

In [4]:
df_riesgo = pd.read_csv('genetic_risk_dataset.csv')
df_riesgo.shape

(8000, 21)

In [5]:
df_riesgo.dtypes

gene_marker_1             float64
gene_marker_2             float64
gene_marker_3             float64
gene_marker_4             float64
gene_marker_5             float64
expression_level_A        float64
expression_level_B        float64
expression_level_C        float64
cholesterol               float64
blood_pressure            float64
glucose                   float64
bmi                       float64
snp_variation_1           float64
snp_variation_2           float64
snp_variation_3           float64
snp_variation_4           float64
gene_expression_risk       object
environmental_exposure     object
smoking_status             object
diet_type                  object
genetic_disorder          float64
dtype: object

In [6]:
print(df_riesgo.isna().sum())

gene_marker_1              339
gene_marker_2              412
gene_marker_3              385
gene_marker_4              394
gene_marker_5              370
expression_level_A         423
expression_level_B         392
expression_level_C         389
cholesterol                378
blood_pressure             388
glucose                    371
bmi                        397
snp_variation_1            410
snp_variation_2            415
snp_variation_3            389
snp_variation_4            412
gene_expression_risk       374
environmental_exposure    2327
smoking_status             414
diet_type                  395
genetic_disorder           419
dtype: int64

In [7]:
##Rellenando de forma mas rapida cada columna

columnas_numericas = df_riesgo.select_dtypes(include = np.number).columns
columnas_categoricas = df_riesgo.select_dtypes(exclude = np.number).columns

imp_num = SimpleImputer(strategy = "mean")
df_riesgo[columnas_numericas] = imp_num.fit_transform(df_riesgo[columnas_numericas])

imp_cat = SimpleImputer(strategy="most_frequent")
df_riesgo[columnas_categoricas] = imp_cat.fit_transform(df_riesgo[columnas_categoricas])

In [8]:
df_riesgo.head()

,gene_marker_1,gene_marker_2,gene_marker_3,gene_marker_4,gene_marker_5,expression_level_A,expression_level_B,expression_level_C,cholesterol,blood_pressure,...,bmi,snp_variation_1,snp_variation_2,snp_variation_3,snp_variation_4,gene_expression_risk,environmental_exposure,smoking_status,diet_type,genetic_disorder
0,54.967142,39.603697,73.189609,24.629012,84.640285,4.292214,6.729085,5.029013,192.427734,109.948075,...,27.048454,0.603012,0.428496,0.213776,0.484405,Low,Low,Never,Poor,1.0
1,48.617357,33.956197,60.589638,29.923818,37.768688,6.519054,5.125383,5.542518,191.956817,122.573965,...,29.592887,0.434190,0.684905,0.596891,0.664882,High,High,Never,Poor,1.0
2,56.476885,37.931501,46.315117,41.403247,56.473080,4.702720,6.007350,5.257735,189.409620,107.950236,...,29.300396,0.765593,0.044835,0.417112,0.770543,Low,High,Current,Average,1.0
3,65.230299,48.576781,60.069673,44.915309,42.639041,5.135854,5.736184,4.372180,231.705485,105.425906,...,12.696281,0.260121,0.324293,0.325863,0.194991,Medium,Moderate,Former,Good,0.0
4,47.658466,55.334280,60.069673,22.568940,73.786021,6.076086,5.981471,4.476266,234.086236,117.035774,...,28.129094,0.622210,0.134407,0.607523,0.580222,High,Moderate,Current,Good,1.0

In [9]:

df_riesgo.isna().sum()

gene_marker_1             0
gene_marker_2             0
gene_marker_3             0
gene_marker_4             0
gene_marker_5             0
expression_level_A        0
expression_level_B        0
expression_level_C        0
cholesterol               0
blood_pressure            0
glucose                   0
bmi                       0
snp_variation_1           0
snp_variation_2           0
snp_variation_3           0
snp_variation_4           0
gene_expression_risk      0
environmental_exposure    0
smoking_status            0
diet_type                 0
genetic_disorder          0
dtype: int64

In [18]:
##puedo sacar el IQ restando el 75% y el 25%
#columnas_ordinales = ['gene_expression_risk', 'enviromental_exposure']
df_codificado = pd.get_dummies(df_riesgo, columns = ['gene_expression_risk'], dtype = int)
df_codificado.head()

,gene_marker_1,gene_marker_2,gene_marker_3,gene_marker_4,gene_marker_5,expression_level_A,expression_level_B,expression_level_C,cholesterol,blood_pressure,...,snp_variation_3,snp_variation_4,environmental_exposure,smoking_status,diet_type,genetic_disorder,gene_expression_risk_High,gene_expression_risk_Low,gene_expression_risk_Medium,gene_expression_risk_Very High
0,54.967142,39.603697,73.189609,24.629012,84.640285,4.292214,6.729085,5.029013,192.427734,109.948075,...,0.213776,0.484405,Low,Never,Poor,1.0,0,1,0,0
1,48.617357,33.956197,60.589638,29.923818,37.768688,6.519054,5.125383,5.542518,191.956817,122.573965,...,0.596891,0.664882,High,Never,Poor,1.0,1,0,0,0
2,56.476885,37.931501,46.315117,41.403247,56.473080,4.702720,6.007350,5.257735,189.409620,107.950236,...,0.417112,0.770543,High,Current,Average,1.0,0,1,0,0
3,65.230299,48.576781,60.069673,44.915309,42.639041,5.135854,5.736184,4.372180,231.705485,105.425906,...,0.325863,0.194991,Moderate,Former,Good,0.0,0,0,1,0
4,47.658466,55.334280,60.069673,22.568940,73.786021,6.076086,5.981471,4.476266,234.086236,117.035774,...,0.607523,0.580222,Moderate,Current,Good,1.0,1,0,0,0

In [21]:
df_coded = pd.get_dummies(df_codificado, columns = ['environmental_exposure'], dtype = int)
df_coded.head()

,gene_marker_1,gene_marker_2,gene_marker_3,gene_marker_4,gene_marker_5,expression_level_A,expression_level_B,expression_level_C,cholesterol,blood_pressure,...,smoking_status,diet_type,genetic_disorder,gene_expression_risk_High,gene_expression_risk_Low,gene_expression_risk_Medium,gene_expression_risk_Very High,environmental_exposure_High,environmental_exposure_Low,environmental_exposure_Moderate
0,54.967142,39.603697,73.189609,24.629012,84.640285,4.292214,6.729085,5.029013,192.427734,109.948075,...,Never,Poor,1.0,0,1,0,0,0,1,0
1,48.617357,33.956197,60.589638,29.923818,37.768688,6.519054,5.125383,5.542518,191.956817,122.573965,...,Never,Poor,1.0,1,0,0,0,1,0,0
2,56.476885,37.931501,46.315117,41.403247,56.473080,4.702720,6.007350,5.257735,189.409620,107.950236,...,Current,Average,1.0,0,1,0,0,1,0,0
3,65.230299,48.576781,60.069673,44.915309,42.639041,5.135854,5.736184,4.372180,231.705485,105.425906,...,Former,Good,0.0,0,0,1,0,0,0,1
4,47.658466,55.334280,60.069673,22.568940,73.786021,6.076086,5.981471,4.476266,234.086236,117.035774,...,Current,Good,1.0,1,0,0,0,0,0,1

In [25]:
Q1 = df_coded[['cholesterol', 'bmi', 'glucose', 'gene_marker_3', 'gene_marker_5']].quantile(0.25)
Q3 = df_coded[['cholesterol', 'bmi', 'glucose', 'gene_marker_3', 'gene_marker_5']].quantile(0.75)
IQR = Q3-Q1

In [26]:
df_sin_atipicos = df_coded[~(df_coded[['cholesterol', 'bmi', 'glucose', 'gene_marker_3', 'gene_marker_5']] > (Q1 - 1.5 * IQR)) | (df_coded[['cholesterol', 'bmi', 'glucose', 'gene_marker_3', 'gene_marker_5']] > (Q3 +1.5 * IQR))]

In [28]:
df_coded.head()

,gene_marker_1,gene_marker_2,gene_marker_3,gene_marker_4,gene_marker_5,expression_level_A,expression_level_B,expression_level_C,cholesterol,blood_pressure,...,smoking_status,diet_type,genetic_disorder,gene_expression_risk_High,gene_expression_risk_Low,gene_expression_risk_Medium,gene_expression_risk_Very High,environmental_exposure_High,environmental_exposure_Low,environmental_exposure_Moderate
0,54.967142,39.603697,73.189609,24.629012,84.640285,4.292214,6.729085,5.029013,192.427734,109.948075,...,Never,Poor,1.0,0,1,0,0,0,1,0
1,48.617357,33.956197,60.589638,29.923818,37.768688,6.519054,5.125383,5.542518,191.956817,122.573965,...,Never,Poor,1.0,1,0,0,0,1,0,0
2,56.476885,37.931501,46.315117,41.403247,56.473080,4.702720,6.007350,5.257735,189.409620,107.950236,...,Current,Average,1.0,0,1,0,0,1,0,0
3,65.230299,48.576781,60.069673,44.915309,42.639041,5.135854,5.736184,4.372180,231.705485,105.425906,...,Former,Good,0.0,0,0,1,0,0,0,1
4,47.658466,55.334280,60.069673,22.568940,73.786021,6.076086,5.981471,4.476266,234.086236,117.035774,...,Current,Good,1.0,1,0,0,0,0,0,1